name: 'changesets-canary-publish'
description: 'changesets canary publish'
runs:
    using: 'node16'
    main: 'dist/index.js'
inputs:
    github_token:
        description: 'github token'
        required: true
    npm_tag:
        description: 'npm tag'
        default: canary
        required: false
    npm_token:
        description: 'npm token'
        required: true
    publish_script:
        description: 'canary deploy script'
        required: true
    packages_dir:
        description: '패키지 디렉터리'
        required: false
        default: 'packages,share'
    excludes:
        description: '제외할 경로'
        required: false
        default: '.github,.changeset'
    version_template:
        description: 'package version template for canary (variables: VERSION, DATE, COMMITID7)'
        required: false
        default: '{VERSION}-canary-{COMMITID7}'
    dry_run:
        description: 'only log packages to canary without publishing'
        required: false
        default: 'false'
    create_release:
        description: 'create release with package and version'
        required: false
        default: 'false'
    language:
        description: 'language for release note, comment etc.'
        required: false
        default: 'en'
