name: 'changesets-canary-publish'
description: 'changesets canary publish to differentiate from normal publish'
runs:
    using: 'node20'
    main: 'dist/index.js'
inputs:
    github_token:
        description: 'github token'
        required: true
    npm_tag:
        description: 'npm tag'
        default: canary
        required: false
    npm_token:
        description: 'npm token (optional if using OIDC trusted publishing)'
        required: false
    publish_script:
        description: 'canary deploy script'
        required: true
    packages_dir:
        description: 'directory to publish'
        required: false
        default: 'packages,share'
    excludes:
        description: 'path to exclude from canary publish'
        required: false
        default: '.github,.changeset'
    version_template:
        description: 'package version template for canary (variables: VERSION, DATE, COMMITID7)'
        required: false
        default: '{VERSION}-canary-{COMMITID7}'
    dry_run:
        description: 'only log packages to canary without publishing'
        required: false
        default: 'false'
    create_release:
        description: 'create release with package and version (If true, you must set `fetch-depth: 0` in @action/checkout)'
        required: false
        default: 'false'
    language:
        description: 'language for release note, comment etc.'
        required: false
        default: 'en'
    provenance:
        description: 'Enable provenance statements (requires npm CLI 11.5.1+, uses OIDC if available)'
        required: false
        default: 'true'
