name: 'changesets-detect-add'
description: 'changeset을 이용한 패키지 배포 플로우를 사용할 때, 해당 PR의 변경점을 파악하여 `.changeset` 하위에 변경된 파일을 기재할 수 있도록 유도하는 action 입니다.'
runs:
    using: 'node20'
    main: 'dist/index.js'
inputs:
    github_token:
        description: 'get github token (필요하면 user의 PAT을 넣어주세요.)'
        required: true
    skip_branches:
        description: 'skip할 브랜치들을 적어주세요.'
        required: false
        default: 'master,main,develop'
    skip_label:
        description: '해당 액션을 skip할 label의 이름을 적어주세요.'
        required: false
        default: 'skip-detect-change'
    packages_dir:
        description: '변경을 탐지할 패키지들의 폴더명을 추가해주세요.'
        required: false
        default: 'packages,share'
    formatting_script:
        description: '.changeset/*.md 파일 포매팅이 필요하다면 script 명령어를 추가해주세요'
        required: false
    excludes:
        description: '제외할 경로'
        required: false
        default: '.github,.changeset'
    language:
        description: 'detect add comment의 언어 설정 (en, ko 중 하나를 설정해주세요.)'
        required: false
        default: 'en'
