name: 'changesets-detect-add'
description: 'Detect changes in the PR and add them to the changeset'
runs:
    using: 'node20'
    main: 'dist/index.js'
inputs:
    github_token:
        description: 'github token to use for the action'
        required: true
    skip_branches:
        description: 'branches to skip the action'
        required: false
        default: 'master,main,develop'
    skip_label:
        description: 'add a label to skip the action'
        required: false
        default: 'skip-detect-change'
    packages_dir:
        description: 'add folder name to detect changes'
        required: false
        default: 'packages,share'
    formatting_script:
        description: 'add a formatting script when needing to format the .changeset/*.md files'
        required: false
    excludes:
        description: 'path to exclude when detecting changes'
        required: false
        default: '.github,.changeset'
    language:
        description: 'language to use for the changeset'
        required: false
        default: 'en'
