name: 'changesets-detect-add'
description: ''
runs:
    using: 'node20'
    main: 'dist/index.js'
inputs:
    github_token:
        description: 'github token to use for the action'
        required: true
    npm_token:
        description: 'npm publish token'
        required: true
    publish_script:
        description: '배포 script'
        required: false
    git_username:
        description: 'username for generating pull request'
        required: false
        default: 'npay-fe-bot'
    git_email:
        description: 'email for generating pull request'
        required: false
        default: 'npay.fe.bot@navercorp.com'
    pr_title:
        description: 'title of pull request'
        required: false
        default: '🚀 version changed packages'
    commit_message:
        description: 'commit message'
        required: false
        default: '📦 bump changed packages version'
    create_github_release_tag:
        description: 'create github release tag'
        required: false
        default: true
    formatting_script:
        description: 'add a formatting script when needing to format the .changeset/*.md files'
        required: false
